task:
  name: Summit_04
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    envSpacing: 11
    episodeLength: 500
    enableDebugVis: true
    useHistory: true
    numHistory: 5
    clipActions: 1.0
    powerScale: 4.0
    controlFrequencyInv: 60
    progressWeight: 0
    distWeight: 0
    reachedGoalWeight: 0
    boxProgressWeight: 0.1
    boxDistWeight: 0.1
    boxReachedGoalWeight: 10
    timeWeight: 0.1
    dofOffsetWeight: 0.05
    plane:
      staticFriction: 0.1
      dynamicFriction: 0.1
      restitution: 0.0
    asset:
      assetFileName: summit_xl_description/robots/summit_xls_std_fixed_camera.urdf
    room_config: square_room_0.yaml
    useBoxes: true
    randomize_box:
      randomize_pos: false
      x_bound:
      - -0.5
      - 1
      y_bound:
      - -1
      - 1
      randomize_rot: true
    randomize_summit:
      randomize_pos: true
      x_bound:
      - -1
      - -0.5
      y_bound:
      - -1
      - 1
      whole_map_start_prob: 0.5
      randomize_rot: true
    randomize_goal:
      randomize_pos: true
      x_bound:
      - -1
      - 1
      y_bound:
      - -1
      - 1
    randomize_box_properties: true
    randomize_summit_properties: false
    randomize_properties:
      box_mass:
      - 0.5
      - 10
      box_friction:
      - 0.05
      - 0.5
      box_width:
      - 0.8
      - 1.5
    enableCameraSensors: false
  sim:
    dt: 0.0166
    substeps: 1
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 4
      num_velocity_iterations: 0
      contact_offset: 0.02
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 10.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 8388608
      num_subscenes: ${....num_subscenes}
      contact_collection: 2
  task:
    randomize: false
    randomization_params:
      frequency: 600
      observations:
        range:
        - 0
        - 0.002
        operation: additive
        distribution: gaussian
      actions:
        range:
        - 0.0
        - 0.02
        operation: additive
        distribution: gaussian
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 256
        - 256
        - 128
        - 128
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:Summit,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      multi_gpu: false
      ppo: true
      mixed_precision: true
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 0.01
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0003
      lr_schedule: adaptive
      schedule_type: legacy
      kl_threshold: 0.008
      score_to_win: 20000
      max_epochs: ${resolve_default:100000,${....max_iterations}}
      save_best_after: 100
      save_frequency: 500
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: false
      e_clip: 0.2
      horizon_length: 16
      minibatch_size: 32768
      mini_epochs: 4
      critic_coef: 2
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.0001
task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 3860
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: true
checkpoint: /home/leon/Documents/summit_xl_gym/runs/Summit/nn/Summit.pth
multi_gpu: false
headless: false
